package com.ronaldpitt.floridalaw;


import android.util.Log;

import java.util.Arrays;

public class ArrayClass {

    final String[] title1Chap = {"Chapter 1 DEFINITIONS", "Chapter 2 COMMON LAW IN FORCE; REPEALED STATUTES"};
    final String[] title2Chap = {"Chapter 6 ADMISSION INTO UNION; CONCESSIONS; STATE BOUNDARIES", "Chapter 7 COUNTY BOUNDARIES", "Chapter 8 CONGRESSIONAL DISTRICTS"};
    final String[] title3Chap = {"Chapter 10 SENATE AND HOUSE OF REPRESENTATIVES", "Chapter 11 LEGISLATIVE ORGANIZATION, PROCEDURES, AND STAFFING"};
    final String[] title4Chap = {"Chapter 14 GOVERNOR", "Chapter 15 SECRETARY OF STATE", "Chapter 16 ATTORNEY GENERAL", "Chapter 17 CHIEF FINANCIAL OFFICER",
            "Chapter 19 COMMISSIONER OF AGRICULTURE", "Chapter 20 ORGANIZATIONAL STRUCTURE", "Chapter 22 EMERGENCY CONTINUITY OF GOVERNMENT", "Chapter 23 MISCELLANEOUS EXECUTIVE FUNCTIONS",
            "Chapter 24 STATE LOTTERIES"};
    final String[] title5Chap = {"Chapter 25 SUPREME COURT", "Chapter 26 CIRCUIT COURTS", "Chapter 27 STATE ATTORNEYS; PUBLIC DEFENDERS; RELATED OFFICES", "Chapter 28 CLERKS OF THE CIRCUIT COURTS",
            "Chapter 29 COURT SYSTEM FUNDING",
    "Chapter 30 SHERIFFS", "Chapter 34 COUNTY COURTS", "Chapter 35 DISTRICT COURTS OF APPEAL", "Chapter 38 JUDGES: GENERAL PROVISIONS", "Chapter 39 PROCEEDINGS RELATING TO CHILDREN", "Chapter 40 JURIES; PAYMENT OF JURORS AND DUE PROCESS COSTS",
            "Chapter 43 COURTS: GENERAL PROVISIONS", "Chapter 44 MEDIATION ALTERNATIVES TO JUDICIAL ACTION"};
    final String[] title6Chap = {"Chapter 45 CIVIL PROCEDURE: GENERAL PROVISIONS", "Chapter 46 PARTIES", "Chapter 47 VENUE", "Chapter 48 PROCESS AND SERVICE OF PROCESS", "Chapter 49 CONSTRUCTIVE SERVICE OF PROCESS", "Chapter 50 LEGAL AND OFFICIAL ADVERTISEMENTS",
    "Chapter 51 SUMMARY PROCEDURE", "Chapter 55 JUDGMENTS", "Chapter 56 FINAL PROCESS", "Chapter 57 COURT COSTS", "Chapter 59 APPELLATE PROCEEDINGS", "Chapter 60 INJUNCTIONS", "Chapter 61 DISSOLUTION OF MARRIAGE; SUPPORT; TIME-SHARING", "Chapter 63 ADOPTION",
    "Chapter 64 PARTITION OF PROPERTY", "Chapter 65 QUIETING TITLE", "Chapter 66 EJECTMENT", "Chapter 68 MISCELLANEOUS PROCEEDINGS", "Chapter 69 MISCELLANEOUS PROCEDURAL MATTERS", "Chapter 70 RELIEF FROM BURDENS ON REAL PROPERTY RIGHTS",
            "Chapter 71 REESTABLISHMENT OF DOCUMENTS", "Chapter 72 TAX MATTERS",
    "Chapter 73 EMINENT DOMAIN", "Chapter 74 PROCEEDINGS SUPPLEMENTAL TO EMINENT DOMAIN", "Chapter 75 BOND VALIDATION", "Chapter 76 ATTACHMENT", "Chapter 77 GARNISHMENT", "Chapter 78 REPLEVIN", "Chapter 79 HABEAS CORPUS", "Chapter 80 QUO WARRANTO",
    "Chapter 81 PROHIBITION", "Chapter 82 FORCIBLE ENTRY AND UNLAWFUL DETAINER", "Chapter 83 LANDLORD AND TENANT", "Chapter 85 ENFORCEMENT OF STATUTORY LIENS", "Chapter 86 DECLARATORY JUDGMENTS", "Chapter 88 UNIFORM INTERSTATE FAMILY SUPPORT ACT"};
    final String[] title7Chap = {"Chapter 90 EVIDENCE CODE", "Chapter 92 WITNESSES, RECORDS, AND DOCUMENTS"};
    final String[] title8Chap = {"Chapter 95 LIMITATIONS OF ACTIONS; ADVERSE POSSESSION"};
    final String[] title9Chap = {"Chapter 97 QUALIFICATION AND REGISTRATION OF ELECTORS", "Chapter 98 REGISTRATION OFFICE, OFFICERS, AND PROCEDURES", "Chapter 99 CANDIDATES", "Chapter 100 GENERAL, PRIMARY, SPECIAL, BOND, AND REFERENDUM ELECTIONS",
            "Chapter 101 VOTING METHODS AND PROCEDURE", "Chapter 102 CONDUCTING ELECTIONS AND ASCERTAINING THE RESULTS",
    "Chapter 103 PRESIDENTIAL ELECTORS; POLITICAL PARTIES; EXECUTIVE COMMITTEES AND MEMBERS", "Chapter 104 ELECTION CODE: VIOLATIONS; PENALTIES", "Chapter 105 NONPARTISAN ELECTIONS", "Chapter 106 CAMPAIGN FINANCING",
            "Chapter 107 CONVENTIONS FOR RATIFYING OR REJECTING PROPOSED AMENDMENTS TO CONSTITUTION OF UNITED STATES"};
    final String[] title10Chap = {"Chapter 110 STATE EMPLOYMENT", "Chapter 111 PUBLIC OFFICERS: GENERAL PROVISIONS", "Chapter 112 PUBLIC OFFICERS AND EMPLOYEES: GENERAL PROVISIONS", "Chapter 113 COMMISSIONS", "Chapter 114 VACATING OFFICE", "Chapter 115 LEAVES OF ABSENCE TO OFFICIALS AND EMPLOYEES",
    "Chapter 116 POWERS AND DUTIES OF OFFICERS", "Chapter 117 NOTARIES PUBLIC", "Chapter 118 - INTERNATIONAL NOTARIES", "Chapter 119 PUBLIC RECORDS", "Chapter 120 ADMINISTRATIVE PROCEDURE ACT", "Chapter 121 FLORIDA RETIREMENT SYSTEM", "Chapter 122 STATE AND COUNTY OFFICERS AND EMPLOYEES RETIREMENT SYSTEM"};
    final String[] title11Chap = {"Chapter 124 COMMISSIONERS' DISTRICTS", "Chapter 125 COUNTY GOVERNMENT", "Chapter 127 RIGHT OF EMINENT DOMAIN TO COUNTIES", "Chapter 129 COUNTY ANNUAL BUDGET", "Chapter 130 COUNTY BONDS", "Chapter 132 GENERAL REFUNDING LAW",
    "Chapter 136 COUNTY DEPOSITORIES", "Chapter 137 BONDS OF COUNTY OFFICERS", "Chapter 138 COUNTY SEATS", "Chapter 142 COUNTY FINE AND FORFEITURE FUND", "Chapter 145 COMPENSATION OF COUNTY OFFICIALS", "Chapter 153 WATER AND SEWER SYSTEMS", "Chapter 154 PUBLIC HEALTH FACILITIES", "Chapter 155 HOSPITALS",
    "Chapter 157 DRAINAGE BY COUNTIES", "Chapter 159 BOND FINANCING", "Chapter 161 BEACH AND SHORE PRESERVATION", "Chapter 162 COUNTY OR MUNICIPAL CODE ENFORCEMENT", "Chapter 163 INTERGOVERNMENTAL PROGRAMS", "Chapter 164 GOVERNMENTAL DISPUTES"};
    final String[] title12Chap = {"Chapter 165 FORMATION OF LOCAL GOVERNMENTS", "Chapter 166 MUNICIPALITIES", "Chapter 170 SUPPLEMENTAL AND ALTERNATIVE METHOD OF MAKING LOCAL MUNICIPAL IMPROVEMENTS", "Chapter 171 LOCAL GOVERNMENT BOUNDARIES", "Chapter 173 FORECLOSURE OF MUNICIPAL TAX AND SPECIAL ASSESSMENT LIENS", "Chapter 175 FIREFIGHTER PENSIONS",
    "Chapter 177 LAND BOUNDARIES", "Chapter 180 MUNICIPAL PUBLIC WORKS", "Chapter 185 MUNICIPAL POLICE PENSIONS"};
    final String[] title13Chap = {"Chapter 186 STATE AND REGIONAL PLANNING", "Chapter 187 STATE COMPREHENSIVE PLAN", "Chapter 189 UNIFORM SPECIAL DISTRICT ACCOUNTABILITY ACT", "Chapter 190 COMMUNITY DEVELOPMENT DISTRICTS", "Chapter 191 INDEPENDENT SPECIAL FIRE CONTROL DISTRICTS"};
    final String[] title14Chap = {"Chapter 192 TAXATION: GENERAL PROVISIONS", "Chapter 193 ASSESSMENTS", "Chapter 194 ADMINISTRATIVE AND JUDICIAL REVIEW OF PROPERTY TAXES", "Chapter 195 PROPERTY ASSESSMENT ADMINISTRATION AND FINANCE", "Chapter 196 EXEMPTION", "Chapter 197 TAX COLLECTIONS, SALES, AND LIENS",
    "Chapter 198 ESTATE TAXES", "Chapter 199 INTANGIBLE PERSONAL PROPERTY TAXES", "Chapter 200 DETERMINATION OF MILLAGE", "Chapter 201 EXCISE TAX ON DOCUMENTS", "Chapter 202 COMMUNICATIONS SERVICES TAX SIMPLIFICATION LAW", "Chapter 203 GROSS RECEIPTS TAXES", "Chapter 205 LOCAL BUSINESS TAXES", "Chapter 206 MOTOR AND OTHER FUEL TAXES",
    "Chapter 207 TAX ON OPERATION OF COMMERCIAL MOTOR VEHICLES", "Chapter 210 TAX ON TOBACCO PRODUCTS", "Chapter 211 TAX ON PRODUCTION OF OIL AND GAS AND SEVERANCE OF SOLID MINERALS", "Chapter 212 TAX ON SALES, USE, AND OTHER TRANSACTIONS", "Chapter 213 STATE REVENUE LAWS: GENERAL PROVISIONS", "Chapter 215 FINANCIAL MATTERS: GENERAL PROVISIONS", "Chapter 216 PLANNING AND BUDGETING", "Chapter 217 SURPLUS PROPERTY",
    "Chapter 218 FINANCIAL MATTERS PERTAINING TO POLITICAL SUBDIVISIONS", "Chapter 219 COUNTY PUBLIC MONEY, HANDLING BY STATE AND COUNTY", "Chapter 220 INCOME TAX CODE"};
    final String[] title15Chap = {"Chapter 222 METHOD OF SETTING APART HOMESTEAD AND EXEMPTIONS"};
    final String[] title16Chap = {"Chapter 238 TEACHERS' RETIREMENT SYSTEM", "Chapter 243 HIGHER EDUCATIONAL FACILITIES BONDS"};
    final String[] title17Chap = {"Chapter 250 MILITARY AFFAIRS", "Chapter 251 FLORIDA STATE DEFENSE FORCE", "Chapter 252 EMERGENCY MANAGEMENT"};
    final String[] title18Chap = {"Chapter 253 STATE LANDS", "Chapter 255 PUBLIC PROPERTY AND PUBLICLY OWNED BUILDINGS", "Chapter 256 FLAGS", "Chapter 257 PUBLIC LIBRARIES AND STATE ARCHIVES", "Chapter 258 STATE PARKS AND PRESERVES", "Chapter 259 LAND ACQUISITIONS FOR CONSERVATION OR RECREATION",
    "Chapter 260 FLORIDA GREENWAYS AND TRAILS ACT", "Chapter 261 OFF-HIGHWAY VEHICLE SAFETY AND RECREATION", "Chapter 265 MEMORIALS, MUSEUMS, AND ARTS AND CULTURE", "Chapter 267 HISTORICAL RESOURCES", "Chapter 270 PUBLIC LANDS", "Chapter 272 CAPITOL CENTER", "Chapter 273 STATE-OWNED TANGIBLE PERSONAL PROPERTY", "Chapter 274 TANGIBLE PERSONAL PROPERTY OWNED BY LOCAL GOVERNMENTS"};
    final String[] title19Chap = {"Chapter 279 REGISTERED PUBLIC OBLIGATIONS", "Chapter 280 SECURITY FOR PUBLIC DEPOSITS", "Chapter 281 SAFETY AND SECURITY SERVICES", "Chapter 282 COMMUNICATIONS AND DATA PROCESSING", "Chapter 283 PUBLIC PRINTING", "Chapter 284 STATE RISK MANAGEMENT AND SAFETY PROGRAMS",
    "Chapter 285 INDIAN RESERVATIONS AND AFFAIRS", "Chapter 286 PUBLIC BUSINESS: MISCELLANEOUS PROVISIONS", "Chapter 287 PROCUREMENT OF PERSONAL PROPERTY AND SERVICES", "Chapter 288 COMMERCIAL DEVELOPMENT AND CAPITAL IMPROVEMENTS", "Chapter 290 URBAN REDEVELOPMENT"};
    final String[] title20Chap = {"Chapter 292 VETERANS' AFFAIRS; SERVICE OFFICERS", "Chapter 295 LAWS RELATING TO VETERANS: GENERAL PROVISIONS", "Chapter 296 VETERANS' HOMES"};
    final String[] title21Chap = {"Chapter 298 DRAINAGE AND WATER CONTROL"};
    final String[] title22Chap = {"Chapter 308 SHIPPING MASTERS", "Chapter 309 PROTECTION OF PORTS AND HARBORS", "Chapter 310 PILOTS, PILOTING, AND PILOTAGE", "Chapter 311 SEAPORT PROGRAMS AND FACILITIES", "Chapter 313 HARBORMASTERS FOR PORTS IN GENERAL", "Chapter 314 HARBORMASTERS FOR CERTAIN PORTS",
    "Chapter 315 PORT FACILITIES FINANCING"};
    final String[] title23Chap = {"Chapter 316 STATE UNIFORM TRAFFIC CONTROL", "Chapter 317 OFF-HIGHWAY VEHICLE TITLING", "Chapter 318 DISPOSITION OF TRAFFIC INFRACTIONS", "Chapter 319 TITLE CERTIFICATES", "Chapter 320 MOTOR VEHICLE LICENSES", "Chapter 321 HIGHWAY PATROL",
    "Chapter 322 DRIVER LICENSES", "Chapter 323 WRECKER OPERATORS", "Chapter 324 FINANCIAL RESPONSIBILITY"};
    final String[] title24Chap = {"Chapter 326 YACHT AND SHIP BROKERS", "Chapter 327 VESSEL SAFETY", "Chapter 328 VESSELS: TITLE CERTIFICATES; LIENS; REGISTRATION"};
    final String[] title25Chap = {"Chapter 329 AIRCRAFT: TITLE; REGISTRATION; LIENS", "Chapter 330 REGULATION OF AIRCRAFT, PILOTS, AND AIRPORTS", "Chapter 331 AVIATION AND AEROSPACE FACILITIES AND COMMERCE", "Chapter 332 AIRPORTS AND OTHER AIR NAVIGATION FACILITIES", "Chapter 333 AIRPORT ZONING"};
    final String[] title26Chap = {"Chapter 334 TRANSPORTATION ADMINISTRATION", "Chapter 335 STATE HIGHWAY SYSTEM", "Chapter 336 COUNTY ROAD SYSTEM", "Chapter 337 CONTRACTING; ACQUISITION, DISPOSAL, AND USE OF PROPERTY", "Chapter 338 LIMITED ACCESS AND TOLL FACILITIES", "Chapter 339 TRANSPORTATION FINANCE AND PLANNING",
    "Chapter 341 PUBLIC TRANSIT", "Chapter 342 WATERWAY AND WATERFRONT IMPROVEMENT", "Chapter 343 REGIONAL TRANSPORTATION", "Chapter 344  COUNTY ROAD AND BRIDGE INDEBTEDNESS", "Chapter 347 FERRIES, TOLL BRIDGES, DAMS, AND LOG DITCHES", "Chapter 348 EXPRESSWAY AND BRIDGE AUTHORITIES", "Chapter 349 JACKSONVILLE TRANSPORTATION AUTHORITY"};
    final String[] title27Chap = {"Chapter 350 FLORIDA PUBLIC SERVICE COMMISSION", "Chapter 351 RAILROADS", "Chapter 354 SPECIAL OFFICERS FOR CARRIERS", "Chapter 361 PUBLIC UTILITIES: SPECIAL POWERS", "Chapter 362 SPECIAL POWERS OF TELEGRAPH AND TELEPHONE COMPANIES", "Chapter 363 TELEGRAPH AND CABLE COMPANIES",
            "Chapter 364 TELECOMMUNICATIONS COMPANIES", "Chapter 365 USE OF TELEPHONES AND FACSIMILE MACHINES", "Chapter 366 PUBLIC UTILITIES", "Chapter 367 WATER AND WASTEWATER SYSTEMS", "Chapter 368 GAS TRANSMISSION AND DISTRIBUTION"};
    final String[] title28Chap = {"Chapter 369 CONSERVATION", "Chapter 373 WATER RESOURCES", "Chapter 374 NAVIGATION DISTRICTS; WATERWAYS DEVELOPMENT", "Chapter 375 OUTDOOR RECREATION AND CONSERVATION LANDS", "Chapter 376 POLLUTANT DISCHARGE PREVENTION AND REMOVAL", "Chapter 377 ENERGY RESOURCES",
    "Chapter 378 LAND RECLAMATION", "Chapter 379 FISH AND WILDLIFE CONSERVATION", "Chapter 380 LAND AND WATER MANAGEMENT"};
    final String[] title29Chap = {"Chapter 381 PUBLIC HEALTH: GENERAL PROVISIONS", "Chapter 382 VITAL STATISTICS", "Chapter 383 MATERNAL AND INFANT HEALTH CARE", "Chapter 384 SEXUALLY TRANSMISSIBLE DISEASES", "Chapter 385 CHRONIC DISEASES", "Chapter 386 PARTICULAR CONDITIONS AFFECTING PUBLIC HEALTH",
    "Chapter 388 MOSQUITO CONTROL", "Chapter 390  TERMINATION OF PREGNANCIES", "Chapter 391 CHILDREN'S MEDICAL SERVICES", "Chapter 392 TUBERCULOSIS CONTROL", "Chapter 393 DEVELOPMENTAL DISABILITIES", "Chapter 394 MENTAL HEALTH", "Chapter 395 HOSPITAL LICENSING AND REGULATION", "Chapter 397 SUBSTANCE ABUSE SERVICES",
    "Chapter 399 ELEVATOR SAFETY", "Chapter 400 NURSING HOMES AND RELATED HEALTH CARE FACILITIES", "Chapter 401 MEDICAL TELECOMMUNICATIONS AND TRANSPORTATION", "Chapter 402 HEALTH AND HUMAN SERVICES: MISCELLANEOUS PROVISIONS", "Chapter 403 ENVIRONMENTAL CONTROL", "Chapter 404 RADIATION", "Chapter 405 MEDICAL INFORMATION AVAILABLE FOR RESEARCH", "Chapter 406 MEDICAL EXAMINERS; DISPOSITION OF HUMAN REMAINS",
    "Chapter 408 HEALTH CARE ADMINISTRATION"};
    final String[] title30Chap = {"Chapter 409 SOCIAL AND ECONOMIC ASSISTANCE", "Chapter 410 AGING AND ADULT SERVICES", "Chapter 411 HANDICAP OR HIGH-RISK CONDITION PREVENTION AND EARLY CHILDHOOD ASSISTANCE", "Chapter 413 EMPLOYMENT AND RELATED SERVICES FOR PERSONS WITH DISABILITIES", "Chapter 414 FAMILY SELF-SUFFICIENCY", "Chapter 415 ADULT PROTECTIVE SERVICES", "Chapter 418 RECREATION DISTRICTS",
    "Chapter 419 COMMUNITY RESIDENTIAL HOMES", "Chapter 420 HOUSING", "Chapter 421 PUBLIC HOUSING", "Chapter 422 HOUSING COOPERATION LAW", "Chapter 423 TAX EXEMPTION OF HOUSING AUTHORITIES", "Chapter 425 RURAL ELECTRIC COOPERATIVES", "Chapter 427 SPECIAL TRANSPORTATION AND COMMUNICATIONS SERVICES", "Chapter 429 ASSISTED CARE COMMUNITIES",
    "Chapter 430 ELDER AFFAIRS"};
    final String[] title31Chap = {"Chapter 435 EMPLOYMENT SCREENING", "Chapter 440 WORKERS' COMPENSATION", "Chapter 441 EMPLOYEES TRUST BENEFIT PLANS", "Chapter 443 REEMPLOYMENT ASSISTANCE", "Chapter 445 WORKFORCE SERVICES", "Chapter 446 JOB TRAINING",
    "Chapter 447 LABOR ORGANIZATIONS", "Chapter 448 GENERAL LABOR REGULATIONS", "Chapter 450 MINORITY LABOR GROUPS", "Chapter 452 BONDS OF EMPLOYEES OF COMMON CARRIERS"};
    final String[] title32Chap = {"Chapter 454 ATTORNEYS AT LAW", "Chapter 455 BUSINESS AND PROFESSIONAL REGULATION: GENERAL PROVISIONS", "Chapter 456 HEALTH PROFESSIONS AND OCCUPATIONS: GENERAL PROVISIONS", "Chapter 457 ACUPUNCTURE", "Chapter 458 MEDICAL PRACTICE", "Chapter 459 OSTEOPATHIC MEDICINE",
    "Chapter 460 CHIROPRACTIC MEDICINE", "Chapter 461 PODIATRIC MEDICINE", "Chapter 462 NATUROPATHY", "Chapter 463 OPTOMETRY", "Chapter 464 NURSING", "Chapter 465 PHARMACY", "Chapter 466 DENTISTRY, DENTAL HYGIENE, AND DENTAL LABORATORIES", "Chapter 467 MIDWIFERY",
    "Chapter 468 MISCELLANEOUS PROFESSIONS AND OCCUPATIONS","Chapter 469 ASBESTOS ABATEMENT", "Chapter 471 ENGINEERING", "Chapter 472 LAND SURVEYING AND MAPPING", "Chapter 473 PUBLIC ACCOUNTANCY", "Chapter 474 VETERINARY MEDICAL PRACTICE", "Chapter 475 REAL ESTATE BROKERS, SALES ASSOCIATES, SCHOOLS, AND APPRAISERS", "Chapter 476 BARBERING", "Chapter 477 COSMETOLOGY",
    "Chapter 478 ELECTROLYSIS", "Chapter 479 OUTDOOR ADVERTISING", "Chapter 480 MASSAGE PRACTICE", "Chapter 481 ARCHITECTURE, INTERIOR DESIGN, AND LANDSCAPE ARCHITECTURE", "Chapter 482 PEST CONTROL", "Chapter 483 HEALTH TESTING SERVICES", "Chapter 484 DISPENSING OF OPTICAL DEVICES AND HEARING AIDS", "Chapter 485 HYPNOSIS",
    "Chapter 486 PHYSICAL THERAPY PRACTICE", "Chapter 487 PESTICIDE REGULATION AND SAFETY", "Chapter 488 COMMERCIAL DRIVING SCHOOLS", "Chapter 489 CONTRACTING", "Chapter 490 PSYCHOLOGICAL SERVICES", "Chapter 491 CLINICAL, COUNSELING, AND PSYCHOTHERAPY SERVICES", "Chapter 492 PROFESSIONAL GEOLOGY", "Chapter 493 PRIVATE INVESTIGATIVE, PRIVATE SECURITY, AND REPOSSESSION SERVICES"};
    final String[] title33Chap = {"Chapter 494 LOAN ORIGINATORS AND MORTGAGE BROKERS", "Chapter 495 REGISTRATION AND PROTECTION OF TRADEMARKS", "Chapter 496 SOLICITATION OF FUNDS", "Chapter 497 FUNERAL, CEMETERY, AND CONSUMER SERVICES", "Chapter 499 FLORIDA DRUG AND COSMETIC ACT", "Chapter 500 FOOD PRODUCTS",
    "Chapter 501 CONSUMER PROTECTION", "Chapter 502 MILK, MILK PRODUCTS, AND FROZEN DESSERTS", "Chapter 504 SPECIALIZED AGRICULTURAL PRODUCT LABELING", "Chapter 506 STAMPED OR MARKED CONTAINERS AND BASKETS", "Chapter 507 HOUSEHOLD MOVING SERVICES", "Chapter 509 LODGING AND FOOD SERVICE ESTABLISHMENTS; MEMBERSHIP CAMPGROUNDS", "Chapter 513 MOBILE HOME AND RECREATIONAL VEHICLE PARKS", "Chapter 514 PUBLIC SWIMMING AND BATHING FACILITIES",
    "Chapter 515 RESIDENTIAL SWIMMING POOL SAFETY ACT", "Chapter 516 CONSUMER FINANCE", "Chapter 517 SECURITIES TRANSACTIONS", "Chapter 518 INVESTMENT OF FIDUCIARY FUNDS", "Chapter 519 EQUITY EXCHANGES", "Chapter 520 RETAIL INSTALLMENT SALES", "Chapter 521 MOTOR VEHICLE LEASE DISCLOSURE", "Chapter 522 COMMISSION MERCHANTS",
    "Chapter 525 GASOLINE AND OIL INSPECTION", "Chapter 526 SALE OF LIQUID FUELS; BRAKE FLUID", "Chapter 527 SALE OF LIQUEFIED PETROLEUM GAS", "Chapter 531 WEIGHTS, MEASURES, AND STANDARDS", "Chapter 532 DEVICES ISSUED IN PAYMENT FOR LABOR", "Chapter 534 LIVESTOCK; MARKS AND BRANDS; STAMPING BEEF", "Chapter 535 HORSE SALES, SHOWS, AND EXHIBITIONS", "Chapter 536 TIMBER AND LUMBER",
    "Chpater 537 TITLE LOANS", "Chapter 538 SECONDHAND DEALERS AND SECONDARY METALS RECYCLERS", "Chapter 539 PAWNBROKING", "Chapter 540 COMMERCIAL DISCRIMINATION", "Chapter 542 COMBINATIONS RESTRICTING TRADE OR COMMERCE", "Chapter 545 COMBINATIONS RESTRICTING FINANCING OF MOTOR VEHICLES", "Chapter 546 AMUSEMENT FACILITIES", "Chapter 548 PUGILISTIC EXHIBITIONS",
    "Chapter 549 AUTOMOBILE RACE MEETS", "Chapter 550 PARI-MUTUEL WAGERING", "Chapter 551 SLOT MACHINES", "Chapter 552 MANUFACTURE, DISTRIBUTION, AND USE OF EXPLOSIVES", "Chapter 553 BUILDING CONSTRUCTION STANDARDS", "Chapter 554 BOILER SAFETY", "Chapter 556 UNDERGROUND FACILITY DAMAGE PREVENTION AND SAFETY", "Chapter 558 CONSTRUCTION DEFECTS",
    "Chapter 559 REGULATION OF TRADE, COMMERCE, AND INVESTMENTS, GENERALLY", "Chapter 560 MONEY SERVICES BUSINESSES"};
    final String[] title34Chap = {"Chapter 561 BEVERAGE LAW: ADMINISTRATION", "Chapter 562 BEVERAGE LAW: ENFORCEMENT", "Chapter 563 BEER AND MALT BEVERAGES", "Chapter 564 WINE", "Chapter 565 LIQUOR", "Chapter 567 LOCAL OPTION ELECTIONS",
    "Chapter 568 INTOXICATING LIQUORS IN COUNTIES WHERE PROHIBITED", "Chapter 569 TOBACCO PRODUCTS"};
    final String[] title35Chap = {"Chapter 570 DEPARTMENT OF AGRICULTURE AND CONSUMER SERVICES", "Chapter 571 AGRICULTURAL ADVERTISING", "Chapter 573 MARKETING OF AGRICULTURAL COMMODITIES", "Chapter 574 SALE OF LEAF TOBACCO", "Chapter 576 AGRICULTURAL FERTILIZERS", "Chapter 578 SEED",
    "Chapter 580 COMMERCIAL FEED AND FEEDSTUFF", "Chapter 581 PLANT INDUSTRY", "Chapter 582 SOIL AND WATER CONSERVATION", "Chapter 583 CLASSIFICATION AND SALE OF EGGS AND POULTRY", "Chapter 585 ANIMAL INDUSTRY", "Chapter 586 HONEY CERTIFICATION AND HONEYBEES", "Chapter 588 LEGAL FENCES AND LIVESTOCK AT LARGE", "Chapter 589 FORESTRY",
    "Chapter 590 FOREST PROTECTION", "Chapter 591 FOREST DEVELOPMENT", "Chapter 593 AGRICULTURAL COMMODITY INSECT CONTROL", "Chapter 595 SCHOOL FOOD AND NUTRITION SERVICES", "Chapter 597 AQUACULTURE", "Chapter 599 VITICULTURE", "Chapter 600 CITRUS MARKETING", "Chapter 601 FLORIDA CITRUS CODE",
    "Chapter 603 FRUITS AND VEGETABLES", "Chapter 604 GENERAL AGRICULTURAL LAWS"};
    final String[] title36Chap = {"Chapter 605 FLORIDA REVISED LIMITED LIABILITY COMPANY ACT", "Chapter 606 BUSINESS COORDINATION", "Chapter 607 FLORIDA BUSINESS CORPORATION ACT", "Chapter 609 COMMON-LAW DECLARATIONS OF TRUST","Chapter 610 CABLE AND VIDEO SERVICES" ,"Chapter 616 PUBLIC FAIRS AND EXPOSITIONS", "Chapter 617 CORPORATIONS NOT FOR PROFIT",
    "Chapter 618 AGRICULTURAL COOPERATIVE MARKETING ASSOCIATIONS", "Chapter 619 NONPROFIT COOPERATIVE ASSOCIATIONS", "Chapter 620 PARTNERSHIP LAWS", "Chapter 621 PROFESSIONAL SERVICE CORPORATIONS AND LIMITED LIABILITY COMPANIES", "Chapter 622 FOREIGN UNINCORPORATED ASSOCIATIONS", "Chapter 623 PRIVATE SCHOOL CORPORATIONS"};
    final String[] title37Chap = {"Chapter 624 INSURANCE CODE: ADMINISTRATION AND GENERAL PROVISIONS", "Chapter 625 ACCOUNTING, INVESTMENTS, AND DEPOSITS BY INSURERS", "Chapter 626 INSURANCE FIELD REPRESENTATIVES AND OPERATIONS", "Chapter 627 INSURANCE RATES AND CONTRACTS", "Chapter 628 STOCK AND MUTUAL INSURERS; HOLDING COMPANIES", "Chapter 629 RECIPROCAL INSURERS",
    "Chapter 630 ALIEN INSURERS: TRUSTEED ASSETS; DOMESTICATION", "Chapter 631 INSURER INSOLVENCY; GUARANTY OF PAYMENT", "Chapter 632 FRATERNAL BENEFIT SOCIETIES", "Chapter 633 FIRE PREVENTION AND CONTROL", "Chapter 634 WARRANTY ASSOCIATIONS", "Chapter 635 MORTGAGE GUARANTY INSURANCE", "Chapter 636 PREPAID LIMITED HEALTH SERVICE ORGANIZATIONS AND DISCOUNT PLAN ORGANIZATIONS", "Chapter 641 HEALTH CARE SERVICE PROGRAMS",
    "Chapter 642 LEGAL EXPENSE INSURANCE", "Chapter 648 BAIL BOND AGENTS", "Chapter 650 SOCIAL SECURITY FOR PUBLIC EMPLOYEES", "Chapter 651 CONTINUING CARE CONTRACTS"};
    final String[] title38Chap = {"Chapter 655 FINANCIAL INSTITUTIONS GENERALLY", "Chapter 657 CREDIT UNIONS", "Chapter 658 BANKS AND TRUST COMPANIES", "Chapter 660 TRUST BUSINESS", "Chapter 662 FAMILY TRUST COMPANIES", "Chapter 663 INTERNATIONAL BANKING",
    "Chapter 665 CAPITAL STOCK ASSOCIATIONS", "Chapter 667 SAVINGS BANKS"};
    final String[] title39Chap = {"Chapter 668 ELECTRONIC COMMERCE", "Chapter 670 UNIFORM COMMERCIAL CODE: FUNDS TRANSFERS", "Chapter 671 UNIFORM COMMERCIAL CODE: GENERAL PROVISIONS", "Chapter 672 UNIFORM COMMERCIAL CODE: SALES", "Chapter 673 UNIFORM COMMERCIAL CODE: NEGOTIABLE INSTRUMENTS", "Chapter 674 UNIFORM COMMERCIAL CODE: BANK DEPOSITS AND COLLECTIONS",
    "Chapter 675 UNIFORM COMMERCIAL CODE: LETTERS OF CREDIT", "Chapter 677 UNIFORM COMMERCIAL CODE: DOCUMENTS OF TITLE", "Chapter 678 UNIFORM COMMERCIAL CODE: INVESTMENT SECURITIES", "Chapter 679 UNIFORM COMMERCIAL CODE: SECURED TRANSACTIONS", "Chapter 680 UNIFORM COMMERCIAL CODE: LEASES", "Chapter 681 MOTOR VEHICLE SALES WARRANTIES", "Chapter 682 ARBITRATION CODE", "Chapter 683 LEGAL HOLIDAYS; SPECIAL OBSERVANCES",
    "Chapter 684 INTERNATIONAL COMMERCIAL ARBITRATION", "Chapter 685 CONTRACT ENFORCEMENT: CHOICE OF LAW", "Chapter 686 SALES, DISTRIBUTION, AND FRANCHISE RELATIONSHIPS", "Chapter 687 INTEREST AND USURY; LENDING PRACTICES", "Chapter 688 UNIFORM TRADE SECRETS ACT"};
    final String[] title40Chap = {"Chapter 689 CONVEYANCES OF LAND AND DECLARATIONS OF TRUST", "Chapter 692 CONVEYANCES BY OR TO PARTICULAR ENTITIES", "Chapter 694 CERTAIN CONVEYANCES MADE VALID", "Chapter 695 RECORD OF CONVEYANCES OF REAL ESTATE", "Chapter 696 RECORD OF CONTRACTS; PHOTOGRAPHIC RECORDING", "Chapter 697 INSTRUMENTS DEEMED MORTGAGES AND THE NATURE OF A MORTGAGE",
    "Chapter 698 CHATTEL MORTGAGES", "Chapter 701 ASSIGNMENT AND CANCELLATION OF MORTGAGES", "Chapter 702 FORECLOSURE OF MORTGAGES AND STATUTORY LIENS", "Chapter 703 ABSTRACTS OF TITLE", "Chapter 704 EASEMENTS", "Chapter 705 LOST OR ABANDONED PROPERTY", "Chapter 707 ESTRAYS", "Chapter 708 MARRIED WOMEN'S PROPERTY",
    "Chapter 709 POWERS OF ATTORNEY AND SIMILAR INSTRUMENTS", "Chapter 710 TRANSFERS TO MINORS", "Chapter 711 FLORIDA UNIFORM TRANSFER-ON-DEATH SECURITY REGISTRATION ACT", "Chapter 712 MARKETABLE RECORD TITLES TO REAL PROPERTY", "Chapter 713 LIENS, GENERALLY", "Chapter 715 PROPERTY: GENERAL PROVISIONS", "Chapter 716 ESCHEATS", "Chapter 717 DISPOSITION OF UNCLAIMED PROPERTY",
    "Chapter 718 CONDOMINIUMS", "Chapter 719 COOPERATIVES", "Chapter 720 HOMEOWNERS' ASSOCIATIONS", "Chapter 721 VACATION AND TIMESHARE PLANS", "Chapter 723 MOBILE HOME PARK LOT TENANCIES"};
    final String[] title41Chap = {"Chapter 725 UNENFORCEABLE CONTRACTS", "Chapter 726 FRAUDULENT TRANSFERS", "Chapter 727 GENERAL ASSIGNMENTS"};
    final String[] title42Chap = {"Chapter 731 PROBATE CODE: GENERAL PROVISIONS", "Chapter 732 PROBATE CODE: INTESTATE SUCCESSION AND WILLS", "Chapter 733 PROBATE CODE: ADMINISTRATION OF ESTATES", "Chapter 734 PROBATE CODE: FOREIGN PERSONAL REPRESENTATIVES; ANCILLARY ADMINISTRATION", "Chapter 735 PROBATE CODE: SMALL ESTATES", "Chapter 736 FLORIDA TRUST CODE",
    "Chapter 738 PRINCIPAL AND INCOME", "Chapter 739 FLORIDA UNIFORM DISCLAIMER OF PROPERTY INTERESTS ACT", "Chapter 740 FIDUCIARY ACCESS TO DIGITAL ASSETS"};
    final String[] title43Chap = {"Chapter 741 MARRIAGE; DOMESTIC VIOLENCE", "Chapter 742 DETERMINATION OF PARENTAGE", "Chapter 743 DISABILITY OF NONAGE OF MINORS REMOVED", "Chapter 744 GUARDIANSHIP", "Chapter 747 CONSERVATORSHIP", "Chapter 751 TEMPORARY CUSTODY OF MINOR CHILDREN BY EXTENDED FAMILY",
    "Chapter 752 GRANDPARENTAL VISITATION RIGHTS", "Chapter 753 SUPERVISED VISITATION"};
    final String[] title44Chap = {"Chapter 760 DISCRIMINATION IN THE TREATMENT OF PERSONS; MINORITY REPRESENTATION", "Chapter 761 RELIGIOUS FREEDOM", "Chapter 765 HEALTH CARE ADVANCE DIRECTIVES"};
    final String[] title45Chap = {"Chapter 766 MEDICAL MALPRACTICE AND RELATED MATTERS", "Chapter 767 DAMAGE BY DOGS; DANGEROUS DOGS", "Chapter 768 NEGLIGENCE", "Chapter 769 HAZARDOUS OCCUPATIONS", "Chapter 770 CIVIL ACTIONS FOR LIBEL", "Chapter 771 ACTIONS FOR ALIENATION OF AFFECTIONS, CRIMINAL CONVERSATION, SEDUCTION, OR BREACH OF CONTRACT TO MARRY",
    "Chapter 772 CIVIL REMEDIES FOR CRIMINAL PRACTICES", "Chapter 773 EQUINE ACTIVITIES", "Chapter 774 ASBESTOS-RELATED AND SILICA-RELATED CLAIMS"};
    final String[] title46Chap = {"Chapter 775 DEFINITIONS; GENERAL PENALTIES; REGISTRATION OF CRIMINALS", "Chapter 776 JUSTIFIABLE USE OF FORCE", "Chapter 777 PRINCIPAL; ACCESSORY; ATTEMPT; SOLICITATION; CONSPIRACY", "Chapter 782 HOMICIDE", "Chapter 784 ASSAULT; BATTERY; CULPABLE NEGLIGENCE", "Chapter 787 KIDNAPPING; FALSE IMPRISONMENT; LURING OR ENTICING A CHILD; CUSTODY OFFENSES",
    "Chapter 790 WEAPONS AND FIREARMS", "Chapter 791 SALE OF FIREWORKS", "Chapter 794 SEXUAL BATTERY", "Chapter 796 PROSTITUTION", "Chapter 797 ABORTION", "Chapter 798 ADULTERY; LEWD AND LASCIVIOUS BEHAVIOR", "Chapter 800 LEWDNESS; INDECENT EXPOSURE", "Chapter 806 ARSON AND CRIMINAL MISCHIEF",
    "Chapter 810 BURGLARY AND TRESPASS", "Chapter 812 THEFT, ROBBERY, AND RELATED CRIMES", "Chapter 815 COMPUTER-RELATED CRIMES", "Chapter 817 FRAUDULENT PRACTICES", "Chapter 818 SALE OF MORTGAGED PERSONAL PROPERTY; SIMILAR OFFENSES", "Chapter 823 PUBLIC NUISANCES", "Chapter 825 ABUSE, NEGLECT, AND EXPLOITATION OF ELDERLY PERSONS AND DISABLED ADULTS",
    "Chapter 826 BIGAMY; INCEST", "Chapter 827 ABUSE OF CHILDREN", "Chapter 828 ANIMALS: CRUELTY; SALES; ANIMAL ENTERPRISE PROTECTION" ,"Chapter 831 FORGERY AND COUNTERFEITING", "Chapter 832 VIOLATIONS INVOLVING CHECKS AND DRAFTS", "Chapter 836 DEFAMATION; LIBEL; THREATENING LETTERS AND SIMILAR OFFENSES", "Chapter 837 PERJURY", "Chapter 838 BRIBERY; MISUSE OF PUBLIC OFFICE", "Chapter 839 OFFENSES BY PUBLIC OFFICERS AND EMPLOYEES",
    "Chapter 843 OBSTRUCTING JUSTICE", "Chapter 847 OBSCENITY", "Chapter 849 GAMBLING", "Chapter 856 DRUNKENNESS; OPEN HOUSE PARTIES; LOITERING; PROWLING; DESERTION", "Chapter 859 POISONS; ADULTERATED DRUGS", "Chapter 860 OFFENSES CONCERNING AIRCRAFT, MOTOR VEHICLES, VESSELS, AND RAILROADS", "Chapter 861 OFFENSES RELATED TO PUBLIC ROADS, TRANSPORT, AND WATERS", "Chapter 865 VIOLATIONS OF CERTAIN COMMERCIAL RESTRICTIONS",
    "Chapter 870 AFFRAYS; RIOTS; ROUTS; UNLAWFUL ASSEMBLIES", "Chapter 871 DISTURBING RELIGIOUS AND OTHER ASSEMBLIES", "Chapter 872 OFFENSES CONCERNING DEAD BODIES AND GRAVES", "Chapter 873 SALE OF ANATOMICAL MATTER", "Chapter 874 CRIMINAL GANG ENFORCEMENT AND PREVENTION", "Chapter 876 CRIMINAL ANARCHY, TREASON, AND OTHER CRIMES AGAINST PUBLIC ORDER", "Chapter 877 MISCELLANEOUS CRIMES", "Chapter 893 DRUG ABUSE PREVENTION AND CONTROL",
    "Chapter 895 OFFENSES CONCERNING RACKETEERING AND ILLEGAL DEBTS", "Chapter 896 OFFENSES RELATED TO FINANCIAL TRANSACTIONS"};
    final String[] title47Chap = {"Chapter 900 GENERAL PROVISIONS", "Chapter 901 ARRESTS", "Chapter 902 PRELIMINARY HEARINGS", "Chapter 903 BAIL", "Chapter 905 GRAND JURY", "Chapter 907 PROCEDURE AFTER ARREST",
    "Chapter 910 JURISDICTION AND VENUE", "Chapter 913 TRIAL JURY", "Chapter 914 WITNESSES; CRIMINAL PROCEEDINGS", "Chapter 916 MENTALLY DEFICIENT AND MENTALLY ILL DEFENDANTS", "Chapter 918 CONDUCT OF TRIAL", "Chapter 921 SENTENCE", "Chapter 922 EXECUTION", "Chapter 923 FORM OF INDICTMENT AND OTHER FORMS",
    "Chapter 924 CRIMINAL APPEALS AND COLLATERAL REVIEW", "Chapter 925 MISCELLANEOUS PROVISIONS OF CRIMINAL PROCEDURE", "Chapter 932 PROVISIONS SUPPLEMENTAL TO CRIMINAL PROCEDURE LAW", "Chapter 933 SEARCH AND INSPECTION WARRANTS", "Chapter 934 SECURITY OF COMMUNICATIONS; SURVEILLANCE", "Chapter 936 INQUESTS OF THE DEAD", "Chapter 937 MISSING PERSON INVESTIGATIONS", "Chapter 938 COURT COSTS",
    "Chapter 939 COSTS", "Chapter 940 EXECUTIVE CLEMENCY", "Chapter 941 CORRECTIONS: INTERSTATE COOPERATION", "Chapter 942 INTERSTATE EXTRADITION OF WITNESSES", "Chapter 943 DEPARTMENT OF LAW ENFORCEMENT", "Chapter 944 STATE CORRECTIONAL SYSTEM", "Chapter 945 DEPARTMENT OF CORRECTIONS", "Chapter 946 INMATE LABOR AND CORRECTIONAL WORK PROGRAMS",
    "Chapter 947 FLORIDA COMMISSION ON OFFENDER REVIEW", "Chapter 948 PROBATION AND COMMUNITY CONTROL", "Chapter 949 PAROLE AND PROBATION: GENERAL PROVISIONS", "Chapter 950 JAILS AND JAILERS", "Chapter 951 COUNTY AND MUNICIPAL PRISONERS", "Chapter 957 CORRECTIONAL PRIVATIZATION", "Chapter 958 YOUTHFUL OFFENDERS", "Chapter 960 VICTIM ASSISTANCE",
    "Chapter 961 VICTIMS OF WRONGFUL INCARCERATION COMPENSATION", "Chapter 984 CHILDREN AND FAMILIES IN NEED OF SERVICES", "Chapter 985 JUVENILE JUSTICE; INTERSTATE COMPACT ON JUVENILES"};
    final String[] title48Chap = {"Chapter 1000 K-20 GENERAL PROVISIONS", "Chapter 1001 K-20 GOVERNANCE", "Chapter 1002 STUDENT AND PARENTAL RIGHTS AND EDUCATIONAL CHOICES", "Chapter 1003 PUBLIC K-12 EDUCATION", "Chapter 1004 PUBLIC POSTSECONDARY EDUCATION",
            "Chapter 1005 NONPUBLIC POSTSECONDARY EDUCATION", "Chapter 1006 SUPPORT FOR LEARNING", "Chapter 1007 ARTICULATION AND ACCESS", "Chapter 1008 ASSESSMENT AND ACCOUNTABILITY", "Chapter 1009 EDUCATIONAL SCHOLARSHIPS, FEES, AND FINANCIAL ASSISTANCE", "Chapter 1010 FINANCIAL MATTERS", "Chapter 1011 PLANNING AND BUDGETING",
    "Chapter 1012 PERSONNEL", "Chapter 1013 EDUCATIONAL FACILITIES"};


    public String[] getArray (int x){
        x = x+1;
        if (x == 1){
            return title1Chap;
        } else if (x ==2){
            return title2Chap;
        } else if (x == 3){
            return title3Chap;
        } else if (x == 4){
            return title4Chap;
        } else if (x ==5){
            return title5Chap;
        } else if (x == 6){
            return title6Chap;
        } else if (x == 7){
            return title7Chap;
        } else if (x == 8){
            return title8Chap;
        } else if (x == 9){
            return title9Chap;
        } else if (x == 10){
            return title10Chap;
        } else if (x == 11){
            return title11Chap;
        } else if (x == 12){
            return title12Chap;
        } else if (x == 13){
            return title13Chap;
        } else if (x == 14){
            return title14Chap;
        } else if (x == 15){
            return title15Chap;
        } else if (x == 16){
            return title16Chap;
        } else if (x == 17){
            return title17Chap;
        } else if (x == 18){
            return title18Chap;
        } else if (x == 19){
            return title19Chap;
        } else if (x == 20){
            return title20Chap;
        } else if (x == 21){
            return title21Chap;
        } else if (x == 22){
            return title22Chap;
        } else if (x == 23){
            return title23Chap;
        } else if (x == 24){
            return title24Chap;
        } else if (x == 25){
            return title25Chap;
        } else if (x == 26){
            return title26Chap;
        } else if (x == 27){
            return title27Chap;
        } else if (x == 28){
            return title28Chap;
        } else if (x == 29){
            return title29Chap;
        } else if (x == 30){
            return title30Chap;
        } else if (x == 31){
            return title31Chap;
        } else if (x == 32){
            return title32Chap;
        } else if (x == 33){
            return title33Chap;
        } else if (x == 34){
            return title34Chap;
        } else if (x == 35){
            return title35Chap;
        } else if (x == 36){
            return title36Chap;
        } else if (x == 37){
            return title37Chap;
        } else if (x == 38){
            return title38Chap;
        } else if (x == 39){
            return title39Chap;
        } else if (x == 40){
            return title40Chap;
        } else if (x == 41){
            return title41Chap;
        } else if (x == 42){
            return title42Chap;
        } else if (x == 43){
            return title43Chap;
        } else if (x == 44){
            return title44Chap;
        } else if (x == 45){
            return title45Chap;
        } else if (x == 46){
            return title46Chap;
        } else if (x == 47){
            return title47Chap;
        } else if (x == 48){
            return title48Chap;
        } else {
            Log.i("getArray Method Problem", "Returning null");
            return null;
        }
    }

}
